### ISSUE TITLE
witsub seems to have been banned from opensubtitles.org

### ISSUE THREAD

**Issue by jbfavre** [nicolargo/witsub#2]
```
$ witsub -l eng -f my_film.mp4
02/05/2016 20:46:13 ERROR - Can not login to XML-RPC server (error: 415 Disabled user agent)
02/05/2016 20:46:13 ERROR - Search return an error (error: 415 Disabled user agent)
Traceback (most recent call last):
  File "/home/jbfavre/.local/bin/witsub", line 11, in <module>
    sys.exit(main())
  File "/home/jbfavre/.local/lib/python2.7/site-packages/witsub/witsub.py", line 539, in main
    subTitle(subdatabase, arg_file, overwrite=arg_overwrite)
  File "/home/jbfavre/.local/lib/python2.7/site-packages/witsub/witsub.py", line 260, in __init__
    self.subtitle = self.__getSubTitle__()
  File "/home/jbfavre/.local/lib/python2.7/site-packages/witsub/witsub.py", line 331, in __getSubTitle__
    ret_subtitle = self.__chooseSubTitle__(rpc_search["data"])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Tried to change value in witsub.py and got another error:

``````
$ witsub -l eng -f my_film.mp4
02/05/2016 20:49:08 ERROR - Can not login to XML-RPC server (error: 414 Unknown User Agent)
02/05/2016 20:49:08 ERROR - Search return an error (error: 414 Unknown User Agent)
Traceback (most recent call last):
  File "/home/jbfavre/.local/bin/witsub", line 11, in <module>
    sys.exit(main())
  File "/home/jbfavre/.local/lib/python2.7/site-packages/witsub/witsub.py", line 539, in main
    subTitle(subdatabase, arg_file, overwrite=arg_overwrite)
  File "/home/jbfavre/.local/lib/python2.7/site-packages/witsub/witsub.py", line 260, in __init__
    self.subtitle = self.__getSubTitle__()
  File "/home/jbfavre/.local/lib/python2.7/site-packages/witsub/witsub.py", line 331, in __getSubTitle__
    ret_subtitle = self.__chooseSubTitle__(rpc_search["data"])
TypeError: 'NoneType' object has no attribute '__getitem__'```
``````

**Comment by jbfavre** [comment]
OK, problem comes from pypi.
Witsub version 1.2 is registered (https://pypi.python.org/pypi/witsub/1.2) but not included in links page (https://pypi.python.org/simple/witsub/).
Therefore a `pip install witsub` will install 1.1 which doesn't work

**Comment by nicolargo** [comment]
Just republish the version 1.2 (now known as 1.2.1) to Pypi.

    pip install --upgrade witsub

And you will have the brand new (old) Witsub version.

Thanks for the head up.
